from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from tools.original_renderer import profile
from tools.original_renderer.bootstrap import (
    DATASET_ID,
    EXPECTED_ADJACENCIES,
    EXPECTED_NATIVE_CROSS_SHARD,
    EXPECTED_NATIVE_TILES,
    ORIGINAL_TILE_ORIGIN,
    EXPECTED_PLAN_FINGERPRINT,
    EXPECTED_SHARDS,
    EXPECTED_TILE_COUNTS,
    EXPECTED_TOTAL_ADJACENCIES,
    EXPECTED_TOTAL_TILES,
    ORIGINAL_SOURCE_PATHS,
    PINNED_PROFILE_FINGERPRINT,
    PINNED_RAW_PROBE_IDS,
    SNAPSHOT_ID,
    WORLD_EXTENT,
)


REPO_ROOT = Path(__file__).resolve().parents[3]
SOURCE_ROOT = REPO_ROOT.parent / "morr-dev"


def _subprocess_json(source: str) -> dict[str, object]:
    completed = subprocess.run(
        (sys.executable, "-c", source),
        cwd=REPO_ROOT,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return json.loads(completed.stdout)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


class OriginalProfileContractTests(unittest.TestCase):
    def test_exact_base_only_input_and_mount_contract(self) -> None:
        self.assertEqual(profile.PROFILE_ID, DATASET_ID)
        self.assertEqual(profile.DATA_DIRECTORIES, ("bsa",))
        self.assertEqual(
            profile.CONTENT_FILES,
            ("Morrowind.esm", "Tribunal.esm", "Bloodmoon.esm"),
        )
        self.assertEqual(
            profile.FALLBACK_ARCHIVES,
            ("Morrowind.bsa", "Tribunal.bsa", "Bloodmoon.bsa"),
        )
        self.assertEqual(len(profile.SOURCE_INPUTS), 6)
        self.assertEqual(
            {Path(item.relative_path).parts[0] for item in profile.SOURCE_INPUTS},
            {"bsa"},
        )
        serialized = json.dumps(
            {
                "directories": profile.DATA_DIRECTORIES,
                "content": profile.CONTENT_FILES,
                "inputs": [item.relative_path for item in profile.SOURCE_INPUTS],
                "cfg": profile.render_openmw_cfg(),
            }
        ).casefold()
        for forbidden in ("tamriel", "fullrest", "tr_mainland", "tamriel_data"):
            self.assertNotIn(forbidden, serialized)

    def test_openmw_config_pins_bloodmoon_weather_texture_aliases(self) -> None:
        self.assertEqual(
            profile.render_openmw_cfg(),
            """# Generated by morrowind-map Stage 4.5. Do not edit.
replace=config
encoding=win1252
fallback-archive=Morrowind.bsa
fallback-archive=Tribunal.bsa
fallback-archive=Bloodmoon.bsa
data="/game/bsa"
content=Morrowind.esm
content=Tribunal.esm
content=Bloodmoon.esm
fallback=Weather_Snow_Cloud_Texture,Tx_BM_Sky_Snow.dds
fallback=Weather_Blizzard_Cloud_Texture,Tx_BM_Sky_Blizzard.dds
""",
        )
        config = profile.render_openmw_cfg().casefold()
        self.assertNotIn("fallback=weather_snow_cloud_texture,tx_sky_snow.dds", config)
        self.assertNotIn(
            "fallback=weather_blizzard_cloud_texture,tx_sky_blizzard.dds",
            config,
        )

    def test_input_hash_allowlist_is_exact(self) -> None:
        self.assertEqual(
            {item.relative_path: item.sha256 for item in profile.SOURCE_INPUTS},
            {
                "bsa/Morrowind.esm": "5c3c8c2cbd20e25901b59b3ece33d36b7ef0e3d60ad8d11828bcc61a5ead1647",
                "bsa/Tribunal.esm": "2ace511f23cc2a9ddd5f3aa59c7919789b9378cf4b17c8ae3375dd6b782f3f2b",
                "bsa/Bloodmoon.esm": "bd27090d0e6ad4c1bf1abc83f1a2dac56fcc82cae7bfe8263c413fb301801357",
                "bsa/Morrowind.bsa": "3dcd5e6bfa08245521a53374bf733ee5c920df49103898a15aa31144ad64cf48",
                "bsa/Tribunal.bsa": "3901e7a146f7a64a4ae9534c80d5974f7ab15adf5c48c4561d9313c0f7831d69",
                "bsa/Bloodmoon.bsa": "7c20956791400d958cb407f0b7c1c19ceaf46719df7eb724d0b450299360bd7c",
            },
        )
        self.assertEqual(
            profile.EXPECTED_ASSET_TREE,
            {
                "files": 6,
                "bytes": 587_905_891,
                "sha256": "42574edf6a23720a2a455d2a3f1b899aa541da330450856e546c5c735fad8083",
            },
        )

    def test_unexpected_file_fails_closed_before_hashing_inputs(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            bsa = Path(directory) / "bsa"
            bsa.mkdir()
            for item in profile.SOURCE_INPUTS:
                (bsa / Path(item.relative_path).name).write_bytes(b"")
            (bsa / "TR_Mainland.esm").write_bytes(b"")
            with self.assertRaisesRegex(ValueError, "exactly the six pinned files"):
                profile.fingerprint_data_directories(Path(directory))

    @unittest.skipUnless((SOURCE_ROOT / "bsa/Morrowind.esm").is_file(), "local GOTY inputs absent")
    def test_local_inputs_recompute_pinned_profile(self) -> None:
        input_audit = profile.validate_source_inputs(SOURCE_ROOT)
        asset_audit = profile.fingerprint_data_directories(SOURCE_ROOT)
        actual = profile.profile_fingerprint(
            input_audit,
            asset_audit=asset_audit,
            openmw_cfg=profile.render_openmw_cfg(),
            settings_cfg=profile.render_settings_cfg(),
        )
        self.assertEqual(actual, PINNED_PROFILE_FINGERPRINT)


class OriginalBootstrapContractTests(unittest.TestCase):
    def test_activation_precedes_import_and_patches_exact_identity(self) -> None:
        value = _subprocess_json(
            """
import json
from pathlib import Path
from tools.original_renderer.bootstrap import activate
p, pub, st, au = activate()
shard = p.explicit_3x3_shard((0, 0))
command = p.docker_batch_command(
    image='original', source_root=Path('/source'), profile_root=Path('/profile'),
    output_root=Path('/out'), shard=shard,
)
mounts = [command[index + 1] for index, item in enumerate(command) if item == '--mount']
print(json.dumps({
    'dataset': p.DATASET_ID,
    'snapshot': p.SNAPSHOT_ID,
    'profile': p.PROFILE_ID,
    'extent': p.POISON_WORLD_EXTENT,
    'origin': [p.POISON_SONG_TILE_GRID.origin_x, p.POISON_SONG_TILE_GRID.origin_y],
    'productionOutput': str(p.DEFAULT_OUTPUT),
    'releaseOutput': str(st.DEFAULT_STABILIZED_OUTPUT),
    'metadataOutput': str(pub.DEFAULT_METADATA_ROOT),
    'image': p.DEFAULT_PRODUCTION_IMAGE,
    'mounts': mounts,
    'contents': p.CONTENT_FILES,
    'dataDirectories': p.DATA_DIRECTORIES,
    'tileCounts': pub.EXPECTED_TILE_COUNTS,
    'crossShard': st.EXPECTED_CROSS_SHARD_EDGES,
    'auditVersion': au.AUDIT_VERSION,
    'openmwCfg': p.render_production_openmw_cfg(),
    'validatorModule': pub.validate_source.__module__,
    'sharedValidator': st.validate_source is pub.validate_source and au.validate_source is pub.validate_source,
}))
"""
        )
        self.assertEqual(value["dataset"], DATASET_ID)
        self.assertEqual(value["snapshot"], SNAPSHOT_ID)
        self.assertEqual(value["profile"], DATASET_ID)
        self.assertEqual(value["extent"], list(WORLD_EXTENT))
        self.assertEqual(value["origin"], [float(value) for value in ORIGINAL_TILE_ORIGIN])
        self.assertEqual(value["productionOutput"], "local-data/openmw-production/original-goty-hd")
        self.assertEqual(value["releaseOutput"], "local-data/openmw-release/original-goty-hd")
        self.assertEqual(value["metadataOutput"], "apps/web/public/datasets/metadata/original-goty-hd")
        self.assertEqual(value["image"], "morrowind-map-openmw:0.51.0-original-hd-v1")
        self.assertEqual(
            value["mounts"],
            [
                "type=bind,src=/source/bsa,dst=/game/bsa,readonly",
                "type=bind,src=/profile,dst=/profile",
                "type=bind,src=/out,dst=/out",
            ],
        )
        self.assertEqual(value["contents"], list(profile.CONTENT_FILES))
        self.assertEqual(value["dataDirectories"], ["bsa"])
        self.assertEqual(
            {int(key): count for key, count in value["tileCounts"].items()},
            EXPECTED_TILE_COUNTS,
        )
        self.assertEqual(value["crossShard"], EXPECTED_NATIVE_CROSS_SHARD)
        self.assertEqual(value["openmwCfg"], profile.render_openmw_cfg())
        self.assertEqual(value["validatorModule"], "tools.original_renderer.publish_contract")
        self.assertIs(value["sharedValidator"], True)

    def test_topology_and_quality_contract_is_pinned(self) -> None:
        self.assertEqual(EXPECTED_TILE_COUNTS, {0: 1, 1: 1, 2: 4, 3: 10, 4: 33, 5: 115, 6: 410, 7: 1540})
        self.assertEqual(EXPECTED_TOTAL_TILES, 2_114)
        self.assertEqual(EXPECTED_NATIVE_TILES, 1_540)
        self.assertEqual(EXPECTED_SHARDS, 198)
        self.assertEqual(EXPECTED_TOTAL_ADJACENCIES, 4_000)
        self.assertEqual(sum(EXPECTED_ADJACENCIES.values()), 4_000)
        self.assertEqual(ORIGINAL_TILE_ORIGIN, (-229_376, 237_568))
        self.assertEqual(EXPECTED_PLAN_FINGERPRINT, "9ad7c36652b18615234819aba986df32a89125b1365d47eddef0f847af90886c")
        self.assertEqual(
            PINNED_RAW_PROBE_IDS,
            (
                "7/25/30:north:7/25/29",
                "7/2/0:east:7/3/0",
            ),
        )

    @unittest.skipUnless((SOURCE_ROOT / "bsa/Morrowind.esm").is_file(), "local GOTY inputs absent")
    def test_local_land_plan_recomputes_exactly(self) -> None:
        source = f"""
import json
from pathlib import Path
from tools.original_renderer.bootstrap import activate
p, pub, _, au = activate()
plugins = p.pinned_poison_plugin_paths(Path({str(SOURCE_ROOT)!r}))
cells = p.derive_effective_land_cells(plugins)
plan = p.plan_report(cells)
native = {{p.native_tile_for_cell(cell) for cell in cells}}
levels = {{7: native}}
for zoom in range(6, -1, -1):
    levels[zoom] = {{p.TileKey(zoom, tile.x // 2, tile.y // 2) for tile in levels[zoom + 1]}}
available = levels[7]
entries = [{{'z': tile.z, 'x': tile.x, 'y': tile.y}} for tiles in levels.values() for tile in tiles]
scope = pub._validate_pinned_tile_topology(entries)
probes = set()
for tile in available:
    for direction, dx, dy in (('east', 1, 0), ('north', 0, -1)):
        neighbor = p.TileKey(7, tile.x + dx, tile.y + dy)
        if neighbor in available and p._shard_center(p.cell_for_native_tile(tile)) != p._shard_center(p.cell_for_native_tile(neighbor)):
            probes.add(f'7/{{tile.x}}/{{tile.y}}:{{direction}}:7/{{neighbor.x}}/{{neighbor.y}}')
print(json.dumps({{
    'targets': plan['targetCount'], 'shards': plan['shardCount'],
    'fingerprint': plan['planFingerprint'],
    'bounds': [min(x for x, y in cells), min(y for x, y in cells), max(x for x, y in cells), max(y for x, y in cells)],
    'counts': {{str(z): len(tiles) for z, tiles in levels.items()}},
    'scope': scope,
    'probesPresent': all(value in probes for value in au.PINNED_RAW_PROBE_IDS),
}}))
"""
        value = _subprocess_json(source)
        self.assertEqual(value["targets"], 1_540)
        self.assertEqual(value["shards"], 198)
        self.assertEqual(value["fingerprint"], EXPECTED_PLAN_FINGERPRINT)
        self.assertEqual(value["bounds"], [-28, -19, 23, 28])
        self.assertEqual(
            {int(key): count for key, count in value["counts"].items()},
            EXPECTED_TILE_COUNTS,
        )
        self.assertIs(value["probesPresent"], True)
        self.assertEqual(
            value["scope"],
            {
                "tiles": 2_114,
                "nativeTiles": 1_540,
                "lowerZoomTiles": 574,
                "allFinalAdjacencies": 4_000,
                "nativeAdjacencies": 2_964,
                "nativeCrossShardAdjacencies": 999,
            },
        )

    def test_activation_fails_if_poison_producer_was_already_imported(self) -> None:
        completed = subprocess.run(
            (
                sys.executable,
                "-c",
                "from tools.openmw_renderer import production; "
                "from tools.original_renderer.bootstrap import activate; activate()",
            ),
            cwd=REPO_ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        self.assertNotEqual(completed.returncode, 0)
        self.assertIn("must start in a fresh subprocess", completed.stderr)

    def test_activation_does_not_modify_frozen_files_or_persist_to_poison(self) -> None:
        frozen = [
            REPO_ROOT / "tools/openmw_renderer" / name
            for name in ("profile.py", "production.py", "publish.py", "stabilize.py", "audit.py")
        ]
        before = {str(path): _sha256(path) for path in frozen}
        activated = _subprocess_json(
            """
import hashlib, json
from pathlib import Path
from tools.original_renderer.bootstrap import activate
root = Path.cwd()
paths = [root / 'tools/openmw_renderer' / name for name in ('profile.py','production.py','publish.py','stabilize.py','audit.py')]
activate()
print(json.dumps({str(path): hashlib.sha256(path.read_bytes()).hexdigest() for path in paths}))
"""
        )
        self.assertEqual(activated, before)
        poison = _subprocess_json(
            """
import json
from tools.openmw_renderer import production, profile, publish, stabilize, audit
print(json.dumps({
    'dataset': production.DATASET_ID, 'profile': profile.PROFILE_ID,
    'tileCount': sum(publish.EXPECTED_TILE_COUNTS.values()),
    'crossShard': stabilize.EXPECTED_CROSS_SHARD_EDGES,
    'auditVersion': audit.AUDIT_VERSION,
}))
"""
        )
        self.assertEqual(poison["dataset"], "poison-song-26.08")
        self.assertEqual(poison["profile"], "poison-song-26.08")
        self.assertEqual(poison["tileCount"], 5_464)
        self.assertEqual(poison["crossShard"], 2_571)
        self.assertEqual(poison["auditVersion"], "poison-basemap-quality-binary-alpha-v4")

    def test_original_source_fingerprint_covers_only_real_original_producer_files(self) -> None:
        self.assertIn("tools/openmw_renderer/production.py", ORIGINAL_SOURCE_PATHS)
        self.assertIn("tools/original_renderer/profile.py", ORIGINAL_SOURCE_PATHS)
        self.assertIn("tools/original_renderer/bootstrap.py", ORIGINAL_SOURCE_PATHS)
        self.assertIn("tools/original_renderer/Dockerfile.production", ORIGINAL_SOURCE_PATHS)
        self.assertNotIn("tools/openmw_renderer/profile.py", ORIGINAL_SOURCE_PATHS)
        self.assertNotIn("tools/openmw_renderer/Dockerfile.production", ORIGINAL_SOURCE_PATHS)
        for relative in ORIGINAL_SOURCE_PATHS:
            self.assertTrue((REPO_ROOT / relative).is_file(), relative)

    def test_dockerfile_has_separate_original_identity(self) -> None:
        dockerfile = (REPO_ROOT / "tools/original_renderer/Dockerfile.production").read_text()
        self.assertIn('io.morrowind-map.dataset="original-goty-hd"', dockerfile)
        self.assertIn(f'io.morrowind-map.snapshot="{SNAPSHOT_ID}"', dockerfile)
        self.assertIn("morrowind-map-openmw-original", dockerfile)
        self.assertNotIn("poison-song-26.08", dockerfile)


if __name__ == "__main__":
    unittest.main()
