from __future__ import annotations

import hashlib
import tempfile
import unittest
from pathlib import Path, PurePosixPath

from tools.openmw_renderer.profile import (
    CONTENT_FILES,
    DATA_DIRECTORIES,
    EXCLUDED_DYNAMIC_CONTENT_FILES,
    FALLBACK_ARCHIVES,
    SOURCE_INPUTS,
    SourceInput,
    fingerprint_data_directories,
    profile_fingerprint,
    render_console_script,
    render_openmw_cfg,
    render_settings_cfg,
    validate_source_inputs,
)


class ProfileContractTests(unittest.TestCase):
    def test_profile_orders_are_exact_and_optional_modules_are_excluded(self) -> None:
        self.assertEqual(
            DATA_DIRECTORIES,
            (
                "bsa",
                "Tamriel Data (SD) 44537 26.08 2026-08-23T18-34Z 9AnoA0Zl/00 Data Files",
                "tamriel/00 Core/Data Files",
            ),
        )
        self.assertEqual(
            FALLBACK_ARCHIVES,
            ("Morrowind.bsa", "Tribunal.bsa", "Bloodmoon.bsa"),
        )
        self.assertEqual(
            CONTENT_FILES,
            (
                "Morrowind.esm",
                "Tribunal.esm",
                "Bloodmoon.esm",
                "Tamriel_Data.esm",
                "TR_Mainland.esm",
            ),
        )
        self.assertEqual(
            EXCLUDED_DYNAMIC_CONTENT_FILES,
            (
                "Tamriel_Data.omwscripts",
                "tamrielrebuilt.omwscripts",
            ),
        )

        serialized_profile = "\n".join(
            (*DATA_DIRECTORIES, *CONTENT_FILES, *EXCLUDED_DYNAMIC_CONTENT_FILES)
        )
        self.assertNotIn("TR_Factions.esp", serialized_profile)
        self.assertNotIn("TR_Firemoth_Vanilla_patch.esp", serialized_profile)
        self.assertNotIn("01 Faction Integration", serialized_profile)
        self.assertNotIn("02 Firemoth Remover", serialized_profile)

    def test_source_inputs_follow_the_pinned_profile_without_optional_esps(self) -> None:
        relative_paths = tuple(source.relative_path for source in SOURCE_INPUTS)
        self.assertEqual(
            relative_paths,
            (
                "bsa/Morrowind.esm",
                "bsa/Tribunal.esm",
                "bsa/Bloodmoon.esm",
                "bsa/Morrowind.bsa",
                "bsa/Tribunal.bsa",
                "bsa/Bloodmoon.bsa",
                "Tamriel Data (SD) 44537 26.08 2026-08-23T18-34Z 9AnoA0Zl/00 Data Files/Tamriel_Data.esm",
                "Tamriel Data (SD) 44537 26.08 2026-08-23T18-34Z 9AnoA0Zl/00 Data Files/Tamriel_Data.omwscripts",
                "tamriel/00 Core/Data Files/TR_Mainland.esm",
                "tamriel/00 Core/Data Files/tamrielrebuilt.omwscripts",
            ),
        )
        self.assertTrue(all(len(source.sha256) == 64 for source in SOURCE_INPUTS))
        self.assertFalse(any(path.lower().endswith(".esp") for path in relative_paths))

    def test_generated_openmw_config_uses_only_container_paths_and_exact_order(self) -> None:
        generated = render_openmw_cfg(game_root=PurePosixPath("/game"))
        expected_lines = (
            "# Generated by morrowind-map Stage 4.5. Do not edit.",
            "replace=config",
            "encoding=win1252",
            "fallback-archive=Morrowind.bsa",
            "fallback-archive=Tribunal.bsa",
            "fallback-archive=Bloodmoon.bsa",
            'data="/game/bsa"',
            'data="/game/Tamriel Data (SD) 44537 26.08 2026-08-23T18-34Z 9AnoA0Zl/00 Data Files"',
            'data="/game/tamriel/00 Core/Data Files"',
            "content=Morrowind.esm",
            "content=Tribunal.esm",
            "content=Bloodmoon.esm",
            "content=Tamriel_Data.esm",
            "content=TR_Mainland.esm",
        )
        self.assertEqual(generated, "\n".join(expected_lines) + "\n")
        self.assertNotIn("/Users/", generated)
        self.assertNotIn("morr-dev", generated)
        self.assertNotIn("TR_Factions", generated)
        self.assertNotIn("Firemoth", generated)
        self.assertNotIn(".omwscripts", generated)

    def test_generated_settings_and_console_configs_are_deterministic(self) -> None:
        first = render_settings_cfg()
        second = render_settings_cfg()
        self.assertEqual(first, second)
        self.assertTrue(first.startswith("# Generated by morrowind-map Stage 4.5."))
        self.assertIn("local map resolution = 512", first)
        self.assertIn("object paging = false", first)
        self.assertNotIn("/Users/", first)
        self.assertEqual(render_console_script((41, -30)), "coe 41 -30\n")

    def test_profile_fingerprint_is_stable_and_covers_config_and_inputs(self) -> None:
        audit = {
            "fixture": {
                "relativePath": "fixture.esm",
                "bytes": 7,
                "sha256": hashlib.sha256(b"fixture").hexdigest(),
            }
        }
        first = profile_fingerprint(audit)
        second = profile_fingerprint(dict(audit))
        changed_input = {
            "fixture": {**audit["fixture"], "bytes": 8},
        }

        self.assertEqual(first, second)
        self.assertNotEqual(first, profile_fingerprint(changed_input))
        self.assertNotEqual(first, profile_fingerprint(audit, openmw_cfg="changed\n"))
        self.assertNotEqual(
            first,
            profile_fingerprint(
                audit,
                asset_audit={
                    "fixture-data": {
                        "files": 1,
                        "bytes": 7,
                        "sha256": hashlib.sha256(b"asset").hexdigest(),
                    }
                },
            ),
        )

    def test_openmw_config_rejects_unsafe_container_root(self) -> None:
        for root in (PurePosixPath('/game"bad'), PurePosixPath("/game\nbad")):
            with self.subTest(root=root):
                with self.assertRaisesRegex(ValueError, "quotes or newlines"):
                    render_openmw_cfg(game_root=root)


class DataDirectoryFingerprintTests(unittest.TestCase):
    @staticmethod
    def _make_asset_tree(
        root: Path,
        *,
        reverse_creation_order: bool = False,
    ) -> None:
        payloads = (
            ("meshes/architecture/example.nif", b"mesh"),
            ("textures/architecture/example.dds", b"texture"),
        )
        for directory_index, relative_root in enumerate(DATA_DIRECTORIES):
            data_root = root / relative_root
            data_root.mkdir(parents=True, exist_ok=True)
            entries = tuple(reversed(payloads)) if reverse_creation_order else payloads
            for relative_path, payload in entries:
                path = data_root / relative_path
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(payload + bytes((directory_index,)))

    def test_fingerprint_is_stable_and_independent_of_creation_order(self) -> None:
        with (
            tempfile.TemporaryDirectory() as first_directory,
            tempfile.TemporaryDirectory() as second_directory,
        ):
            first_root = Path(first_directory)
            second_root = Path(second_directory)
            self._make_asset_tree(first_root)
            self._make_asset_tree(second_root, reverse_creation_order=True)

            first = fingerprint_data_directories(first_root)
            second = fingerprint_data_directories(second_root)

            self.assertEqual(first, fingerprint_data_directories(first_root))
            self.assertEqual(first, second)
            self.assertEqual(tuple(first), DATA_DIRECTORIES)
            self.assertTrue(all(item["files"] == 2 for item in first.values()))

    def test_mutating_one_loose_asset_changes_only_its_tree_fingerprint(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self._make_asset_tree(root)
            baseline = fingerprint_data_directories(root)
            changed_tree = DATA_DIRECTORIES[1]
            changed_path = root / changed_tree / "textures/architecture/example.dds"
            changed_path.write_bytes(changed_path.read_bytes() + b"changed")

            mutated = fingerprint_data_directories(root)

            self.assertNotEqual(mutated[changed_tree], baseline[changed_tree])
            for unchanged_tree in (DATA_DIRECTORIES[0], DATA_DIRECTORIES[2]):
                self.assertEqual(mutated[unchanged_tree], baseline[unchanged_tree])

    def test_symlink_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self._make_asset_tree(root)
            target = root / "outside-resource.nif"
            target.write_bytes(b"outside")
            link = root / DATA_DIRECTORIES[0] / "meshes/linked-resource.nif"
            try:
                link.symlink_to(target)
            except OSError as error:
                self.skipTest(f"symlinks unavailable on this filesystem: {error}")

            with self.assertRaisesRegex(ValueError, "cannot contain symlinks"):
                fingerprint_data_directories(root)

    def test_case_insensitive_resource_collision_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            for relative_root in DATA_DIRECTORIES:
                (root / relative_root).mkdir(parents=True, exist_ok=True)
            data_root = root / DATA_DIRECTORIES[0]
            upper = data_root / "Meshes/Example.NIF"
            lower = data_root / "meshes/example.nif"
            upper.parent.mkdir(parents=True)
            upper.write_bytes(b"upper")
            if lower.exists():
                self.skipTest("case-collision fixture requires a case-sensitive filesystem")
            lower.parent.mkdir(parents=True)
            lower.write_bytes(b"lower")

            with self.assertRaisesRegex(
                ValueError,
                "Case-insensitive OpenMW resource collision",
            ):
                fingerprint_data_directories(root)


class SourceValidationTests(unittest.TestCase):
    def test_validation_succeeds_and_reports_bytes_and_hash(self) -> None:
        payloads = {
            "base/Morrowind.esm": b"base",
            "mods/TR_Mainland.esm": b"mainland",
        }
        inputs = tuple(
            SourceInput(logical_id, relative_path, hashlib.sha256(payload).hexdigest())
            for logical_id, (relative_path, payload) in zip(
                ("base", "mainland"), payloads.items(), strict=True
            )
        )
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            for relative_path, payload in payloads.items():
                path = root / relative_path
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(payload)

            audit = validate_source_inputs(root, inputs)

        self.assertEqual(tuple(audit), ("base", "mainland"))
        self.assertEqual(
            audit["base"],
            {
                "relativePath": "base/Morrowind.esm",
                "bytes": 4,
                "sha256": hashlib.sha256(b"base").hexdigest(),
            },
        )
        self.assertEqual(audit["mainland"]["bytes"], len(b"mainland"))

    def test_validation_rejects_hash_mismatch(self) -> None:
        source = SourceInput("fixture", "fixture.esm", hashlib.sha256(b"expected").hexdigest())
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / source.relative_path).write_bytes(b"actual")
            with self.assertRaisesRegex(
                ValueError,
                r"hash mismatch for fixture\.esm: expected [0-9a-f]{64}, got [0-9a-f]{64}",
            ):
                validate_source_inputs(root, (source,))

    def test_validation_rejects_missing_file(self) -> None:
        source = SourceInput("fixture", "missing.esm", hashlib.sha256(b"expected").hexdigest())
        with tempfile.TemporaryDirectory() as directory:
            with self.assertRaisesRegex(FileNotFoundError, "Required OpenMW input is missing"):
                validate_source_inputs(Path(directory), (source,))


if __name__ == "__main__":
    unittest.main()
