export {
  ARTIFACT_SCHEMA_VERSION,
  DATASET_SCHEMA_VERSION,
  TES3_CELL_SIZE,
  TES3_PROJECTION_CODE,
} from "./types";
export type {
  ArtifactReference,
  ContentFileDescriptor,
  ContentFileInclusion,
  ContentFileKind,
  DataDirectoryDescriptor,
  DatasetArtifacts,
  DatasetIndex,
  DatasetIndexEntry,
  DatasetManifest,
  DatasetReadiness,
  DatasetSchemaVersion,
  Extent,
  Locale,
  LocationCatalog,
  LocaleArtifactReference,
  LocaleDescriptor,
  LocaleStatus,
  LocalizationDescriptor,
  LocalizedText,
  MapDescriptor,
  MapAssetsManifest,
  MapKey,
  ModuleDescriptor,
  ModuleStatus,
  Point,
  PlaceEntrance,
  PlaceLocaleCatalog,
  PlaceLocaleRecord,
  PlaceRecord,
  PlaceSource,
  PlaceSourceKind,
  PlaceType,
  ProfileItemStatus,
  ProfileStatus,
  ProjectionDescriptor,
  ProvenanceDescriptor,
  ReadinessDescriptor,
  RegionDescriptor,
  RegionKind,
  RegionStatus,
  RegisteredArchiveDescriptor,
  ReleaseDescriptor,
  SourceProfileDescriptor,
  StaticRasterLayer,
  Tes3CellSize,
  Tes3ProjectionCode,
  TileGridDescriptor,
  TileSetReference,
} from "./types";
export {
  ContractValidationError,
  getDatasetIndexValidationIssues,
  getDatasetManifestValidationIssues,
  getLocationCatalogValidationIssues,
  getMapAssetsManifestValidationIssues,
  getPlaceLocaleCatalogValidationIssues,
  isDatasetIndex,
  isDatasetManifest,
  isLocationCatalog,
  isMapAssetsManifest,
  isPlaceLocaleCatalog,
  parseDatasetIndex,
  parseDatasetManifest,
  parseLocationCatalog,
  parseMapAssetsManifest,
  parsePlaceLocaleCatalog,
} from "./validation";
export type { ContractKind, ContractValidationIssue } from "./validation";

export { default as datasetIndexSchema } from "./schemas/dataset-index.schema.json";
export { default as datasetManifestSchema } from "./schemas/dataset-manifest.schema.json";
export { default as locationCatalogSchema } from "./schemas/location-catalog.schema.json";
export { default as mapAssetsSchema } from "./schemas/map-assets.schema.json";
export { default as placeLocaleCatalogSchema } from "./schemas/place-locale-catalog.schema.json";
